version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "9renpoto"
    default_assignees:
      - "9renpoto"
    default_labels:
      - "Type: Dependencies"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
  - package_manager: "javascript"
    directory: "/apps/me"
    update_schedule: "live"
    default_reviewers:
      - "9renpoto"
    default_assignees:
      - "9renpoto"
    default_labels:
      - "Type: Dependencies"

    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
      - match:
          dependency_type: "development"
          update_type: "all"
