version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    default_reviewers:
      - '9renpoto'
    default_assignees:
      - '9renpoto'
    default_labels:
      - 'Type: Dependencies'
    allowed_updates:
      - match:
          update_type: 'security'
